[package]
name = "emb-editor"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
emb-data = { path = "../../crates/emb-data" }
emb-draw = { path = "../../crates/emb-draw" }
emb-model = { path = "../../crates/emb-model" }
eframe = { version = "0.35", default-features = false, features = ["glow", "default_fonts"] }
rfd = "0.17"
